server:
  forward-headers-strategy: native

spring:
  jpa:
    properties:
      hibernate:
        format_sql: false
        show_sql: false
  mail:
    host: smtp-relay.brevo.com
    port: 2525
    username: ${BREVO_USERNAME}
    password: ${BREVO_SMTP_KEY}
    from: noreply@timiworkshop.online
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: ${GOOGLE_REDIRECT_URI}

management:
  health:
    mail:
      enabled: false

logging:
  level:
    root: info
    org.hibernate: WARN
